services:
  conf-fix:
    image: conf-fixtures
    build: .
    restart: unless-stopped
    volumes:
      - ./slides/images:/usr/share/nginx/html/images/:ro
      - ./slides/css:/usr/share/nginx/html/css/:ro
      - ./slides/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "9577:80"