framework:
    workflows:
        vel_order:
            type: state_machine
            audit_trail: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order
            initial_marking: !php/const App\Entity\Order::INITIAL
            metadata:
                schema:
                    direction: TD
                styles:
                    places:
                        client:
                            bg_color: '#359A58'
                            color: white
                            shape: hexagon
                            stroke-width: 1px
                            stroke-color: black
                        merchant:
                            bg_color: '#9A5713'
                            color: white
                            shape: rounded
                            stroke-width: 1px
                            stroke-color: black
                        anonymous:
                            bg_color: red
                            color: white
                            shape: stadium
                            stroke-width: 1px
                            stroke-color: black
                        technical:
                            bg_color: '#25729A'
                            color: white
                            shape: rounded
                            stroke-width: 1px
                            stroke-color: black
                    transitions:
                        client:
                            color: '#359A58'
                        #    width: 2px
                        merchant:
                            color: '#9A5713'
                            width: 2px
                        anonymous:
                            color: red
                            width: 2px
                        technical:
                            color: '#25729A'
                            width: 2px
                            link-style: dotted

            places:
                !php/const App\Entity\Order::INITIAL:
                    metadata:
                        style: anonymous
                        shape: rhombus
                !php/const App\Entity\Order::OUTDATED:
                    metadata:
                        style: anonymous
                !php/const App\Entity\Order::COMPLETED:
                    metadata:
                        style: client
                !php/const App\Entity\Order::PAYMENT_REFUSED:
                    metadata:
                        style: client
                !php/const App\Entity\Order::PAYMENT_ACCEPTED:
                    metadata:
                        style: client
                !php/const App\Entity\Order::PAYMENT_PENDING:
                    metadata:
                        style: client
                !php/const App\Entity\Order::SUPPLYING_IN_PROGRESS:
                    metadata:
                        style: technical
                !php/const App\Entity\Order::DELIVERY_TO_PREPARE:
                    metadata:
                       style: merchant
                !php/const App\Entity\Order::READY_TO_SHIP:
                    metadata:
                       style: technical
                !php/const App\Entity\Order::SHIPPED:
                    metadata:
                       style: technical
                !php/const App\Entity\Order::DELIVERED:
                    metadata:
                        style: merchant
                !php/const App\Entity\Order::FINISHED:
                    metadata:
                        style: client
                !php/const App\Entity\Order::IN_LITIGATION:
                    metadata:
                        style: client
                !php/const App\Entity\Order::LITIGATION_HANDLED:
                    metadata:
                        style: merchant

            transitions:
                link_order_to_user:
                    guard: "is_granted('ROLE_CLIENT') and (subject.getUser() == null or subject.getUser() == user)"
                    from: !php/const App\Entity\Order::INITIAL
                    to: !php/const App\Entity\Order::COMPLETED
                    metadata:
                        style: client
                cancel_old_order:
                    guard: "is_granted('ROLE_TECHNICAL')"
                    from: !php/const App\Entity\Order::INITIAL
                    to: !php/const App\Entity\Order::OUTDATED
                    metadata:
                        style: technical
                        link-style: dotted
                create_payment:
                    guard: "is_granted('ROLE_CLIENT') and subject.getUser() == user"
                    from: [!php/const App\Entity\Order::COMPLETED, !php/const App\Entity\Order::PAYMENT_REFUSED]
                    to: payment_pending
                    metadata:
                        style: client
                accept_payment:
                    guard: "is_granted('ROLE_TECHNICAL')"
                    from: !php/const App\Entity\Order::PAYMENT_PENDING
                    to: !php/const App\Entity\Order::PAYMENT_ACCEPTED
                    metadata:
                        style: technical
                        link-style: dotted
                refuse_payment:
                    guard: "is_granted('ROLE_TECHNICAL')"
                    from: !php/const App\Entity\Order::PAYMENT_PENDING
                    to: !php/const App\Entity\Order::PAYMENT_REFUSED
                    metadata:
                        style: technical
                        link-style: dotted
                confirm_provisioning:
                    guard: "is_granted('ROLE_MERCHANT')"
                    from: [!php/const App\Entity\Order::PAYMENT_ACCEPTED, !php/const App\Entity\Order::SUPPLYING_IN_PROGRESS]
                    to: !php/const App\Entity\Order::DELIVERY_TO_PREPARE
                    metadata:
                        style: merchant
                delay_order_supplying_in_progress:
                    guard: "is_granted('ROLE_MERCHANT')"
                    from: [!php/const App\Entity\Order::PAYMENT_ACCEPTED]
                    to: !php/const App\Entity\Order::SUPPLYING_IN_PROGRESS
                    metadata:
                        style: merchant
                        link-size: longer

                prepare_delivery:
                    guard: "is_granted('ROLE_MERCHANT')"
                    from: !php/const App\Entity\Order::DELIVERY_TO_PREPARE
                    to: !php/const App\Entity\Order::READY_TO_SHIP
                    metadata:
                        style: merchant
                ship:
                    guard: "is_granted('ROLE_TECHNICAL')"
                    from: !php/const App\Entity\Order::READY_TO_SHIP
                    to: !php/const App\Entity\Order::SHIPPED
                    metadata:
                        style: technical
                        link-style: dotted
                deliver:
                    guard: "is_granted('ROLE_TECHNICAL')"
                    from: !php/const App\Entity\Order::SHIPPED
                    to: !php/const App\Entity\Order::DELIVERED
                    metadata:
                        style: technical
                        link-style: dotted
                reject_delivery:
                    guard: "is_granted('ROLE_CLIENT') and subject.getUser() == user"
                    from: !php/const App\Entity\Order::DELIVERED
                    to: !php/const App\Entity\Order::IN_LITIGATION
                    metadata:
                        style: client
                confirm_delivery:
                    guard: "is_granted('ROLE_CLIENT') and subject.getUser() == user"
                    from: !php/const App\Entity\Order::DELIVERED
                    to: !php/const App\Entity\Order::FINISHED
                    metadata:
                        style: client
                        link-size: longer
                handle_litigation:
                    guard: "is_granted('ROLE_MERCHANT')"
                    from: !php/const App\Entity\Order::IN_LITIGATION
                    to: !php/const App\Entity\Order::LITIGATION_HANDLED
                    metadata:
                        style: merchant
                close_litigation:
                    guard: "is_granted('ROLE_CLIENT') and subject.getUser() == user"
                    from: !php/const App\Entity\Order::IN_LITIGATION
                    to: !php/const App\Entity\Order::FINISHED
                    metadata:
                        style: client