CREATE USER keycloak WITH PASSWORD 'keycloak';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

CREATE USER back WITH PASSWORD 'back';
CREATE DATABASE back;
GRANT ALL PRIVILEGES ON DATABASE back TO back;
